version: "3"
services:
  node-app:
    build:
      context: ./api
      target: development
    volumes:
      - ./api/src:/app/src:ro
    environment:
      - NOD_ENV=development
    command: npm run start-dev